print "testing format"
print "testing \\ format backslash"
print "testing \' format quote"
print "testing \" format double quote"
print "testing \a format a"
print "testing \b format b"
print "testing \f format f"
print "testing \n format n"
print "testing \r format r"
print "testing \t format t"
print "testing \v format v"
